apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: farlands-live-backend
rules:
  - apiGroups: [""]
    resources: [namespaces, serviceaccounts, secrets, configmaps, services, pods, pods/log, persistentvolumeclaims, resourcequotas, limitranges]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [apps]
    resources: [deployments]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [networking.k8s.io]
    resources: [networkpolicies]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [batch]
    resources: [jobs, cronjobs]
    verbs: [get, list, watch, create, update, patch, delete]
  - apiGroups: [coordination.k8s.io]
    resources: [leases]
    verbs: [get, create, update, delete]
  - apiGroups: [rbac.authorization.k8s.io]
    resources: [rolebindings]
    verbs: [get, create, update, patch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: farlands-live-backend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: farlands-live-backend
subjects:
  - kind: ServiceAccount
    name: farlands-backend
    namespace: dev-deployment
